[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["yang-lin94 <casongg@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
matplotlib = "^3.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
